"""German semantic detection terms."""

from __future__ import annotations

PACK = {
    "id": "de",
    "name": "German",
    "security_sensitive_phrases": {
        "password reset": [
            "passwort zurücksetzen",
            "setzen sie ihr passwort zurück",
            "passwort ändern",
            "passwort vergessen",
            "passwort wiederherstellen",
        ],
        "account recovery": [
            "kontowiederherstellung",
            "konto wiederherstellen",
            "account wiederherstellen",
        ],
        "one-time code": [
            "einmalcode",
            "einmaliger code",
            "temporäres passwort",
            "temporärer code",
        ],
        "multi-factor auth": [
            "zwei-faktor-authentifizierung",
            "zwei faktor authentifizierung",
            "zweistufige verifizierung",
            "mehrfaktor-authentifizierung",
            "2fa",
            "mfa",
        ],
        "magic link": [
            "magischer link",
            "login-link",
        ],
        "account verification": [
            "bestätigen sie ihre e-mail",
            "verifizieren sie ihr konto",
            "bestätigen sie ihr konto",
            "identität bestätigen",
            "kontoverifizierung",
        ],
        "account confirmation": [
            "konto bestätigen",
            "e-mail bestätigen",
            "kontobestätigung",
        ],
        "security alert": [
            "sicherheitswarnung",
            "neue anmeldung",
            "neuer login",
            "verdächtige anmeldung",
            "verdächtige aktivität",
            "unautorisierte aktivität",
        ],
        "security key change": [
            "ssh-schlüssel hinzugefügt",
            "ssh schlüssel hinzugefügt",
            "ssh-schlüssel entfernt",
            "öffentlicher schlüssel hinzugefügt",
            "gpg-schlüssel hinzugefügt",
        ],
    },
    "auth_code_labels": [
        "code",
        "otp",
        "pin",
        "bestätigungscode",
        "verifizierungscode",
        "authentifizierungscode",
        "anmeldecode",
        "sicherheitscode",
    ],
    "private_field_labels": [
        "e-mail",
        "email",
        "telefon",
        "adresse",
        "kontakt",
        "teilnehmer",
        "empfänger",
        "absender",
        "vollständiger name",
        "vorname",
        "nachname",
        "geburtsdatum",
        "reisepass",
    ],
    "browser_private_context_terms": [
        "angemeldet",
        "abmelden",
        "logout",
        "mein konto",
        "konto",
        "profil",
        "authentifiziert",
        "passwort",
    ],
    "redaction_markers": [
        "betreff sensibler e-mail redigiert",
        "inhalt sensibler e-mail redigiert",
        "sensible e-mail-nachricht redigiert",
    ],
    "redacted_security_terms": [
        "passwort",
        "zurücksetzen",
        "wiederherstellen",
        "bestätigen",
        "verifizierung",
        "authentifizierung",
        "anmeldung",
        "code",
        "sicherheit",
        "schlüssel",
    ],
    "security_link_terms": [
        "reset",
        "verify",
        "confirm",
        "zuruecksetzen",
        "zurücksetzen",
        "wiederherstellen",
        "bestaetigen",
        "bestätigen",
        "passwort",
        "code",
    ],
}
