"""English semantic detection terms."""

from __future__ import annotations

PACK = {
    "id": "en",
    "name": "English",
    "security_sensitive_phrases": {
        "password reset": [
            "password reset",
            "password change",
            "password recovery",
            "reset your password",
            "reset the password",
            "forgot your password",
            "forgot my password",
        ],
        "account recovery": [
            "account recovery",
        ],
        "one-time code": [
            "one-time code",
            "one time code",
            "one-time password",
            "temporary password",
            "temporary code",
            "one time",
        ],
        "multi-factor auth": [
            "2fa",
            "two-factor",
            "two factor",
            "multi-factor",
            "multi factor",
            "mfa",
        ],
        "magic link": [
            "magic link",
        ],
        "account verification": [
            "verify your email",
            "verify your account",
            "verify your identity",
            "account verification",
            "email verification",
        ],
        "account confirmation": [
            "confirm your email",
            "confirm your account",
            "confirm your identity",
            "account confirmation",
            "email confirmation",
        ],
        "security alert": [
            "security alert",
            "new sign-in",
            "new sign in",
            "new login",
            "suspicious sign-in",
            "suspicious sign in",
            "suspicious login",
            "suspicious activity",
            "unauthorized sign-in",
            "unauthorized sign in",
            "unauthorized login",
            "unauthorized activity",
        ],
        "security key change": [
            "public key added",
            "public key removed",
            "public key was added",
            "public key was removed",
            "new public key was added",
            "ssh key added",
            "ssh key removed",
            "ssh key was added",
            "ssh key was removed",
            "new ssh key was added",
            "gpg key added",
            "gpg key removed",
            "gpg key was added",
            "gpg key was removed",
            "deploy key added",
            "deploy key removed",
            "deploy key was added",
            "deploy key was removed",
            "a new public key was added",
            "a new ssh key was added",
        ],
    },
    "auth_code_labels": [
        "code",
        "otp",
        "passcode",
        "pin",
        "verification code",
        "authentication code",
        "login code",
        "security code",
        "one-time code",
        "one time code",
    ],
    "private_field_labels": [
        "email",
        "phone",
        "address",
        "contact",
        "attendee",
        "recipient",
        "sender",
        "full name",
        "first name",
        "last name",
        "dob",
        "date of birth",
        "ssn",
        "passport",
    ],
    "browser_private_context_terms": [
        "logged in",
        "sign out",
        "logout",
        "account",
        "profile",
        "authenticated",
        "authentication",
        "prefilled",
        "password",
    ],
    "redaction_markers": [
        "sensitive email subject redacted",
        "sensitive email content redacted",
        "sensitive email body redacted",
        "sensitive email message redacted",
        "redacted sensitive email subject",
        "redacted sensitive subject",
    ],
    "redacted_security_terms": [
        "password",
        "reset",
        "recover",
        "verify",
        "verification",
        "auth",
        "authentication",
        "login",
        "sign-in",
        "sign in",
        "one-time",
        "one time",
        "otp",
        "2fa",
        "token",
        "passcode",
        "code",
        "security",
        "magic",
        "key",
    ],
    "security_link_terms": [
        "reset",
        "recover",
        "verify",
        "confirm",
        "magic",
        "otp",
        "2fa",
    ],
}
