"""Spanish semantic detection terms."""

from __future__ import annotations

PACK = {
    "id": "es",
    "name": "Spanish",
    "security_sensitive_phrases": {
        "password reset": [
            "restablecer contraseña",
            "restablecer tu contraseña",
            "restablecer la contraseña",
            "recuperar contraseña",
            "recuperar tu contraseña",
            "cambiar contraseña",
            "cambiar tu contraseña",
            "olvidaste tu contraseña",
        ],
        "account recovery": [
            "recuperación de cuenta",
            "recuperar cuenta",
            "recuperar tu cuenta",
        ],
        "one-time code": [
            "código de un solo uso",
            "codigo de un solo uso",
            "contraseña temporal",
            "contrasena temporal",
            "código temporal",
            "codigo temporal",
        ],
        "multi-factor auth": [
            "autenticación de dos factores",
            "autenticacion de dos factores",
            "verificación en dos pasos",
            "verificacion en dos pasos",
            "2fa",
            "mfa",
        ],
        "magic link": [
            "enlace mágico",
            "enlace magico",
        ],
        "account verification": [
            "verifica tu correo",
            "verificar tu correo",
            "verifica tu cuenta",
            "verificar tu cuenta",
            "verifica tu identidad",
            "verificar tu identidad",
            "verificación de cuenta",
            "verificacion de cuenta",
        ],
        "account confirmation": [
            "confirma tu correo",
            "confirmar tu correo",
            "confirma tu cuenta",
            "confirmar tu cuenta",
            "confirma tu identidad",
            "confirmar tu identidad",
        ],
        "security alert": [
            "alerta de seguridad",
            "nuevo inicio de sesión",
            "nuevo inicio de sesion",
            "inicio de sesión sospechoso",
            "inicio de sesion sospechoso",
            "actividad sospechosa",
            "inicio de sesión no autorizado",
            "inicio de sesion no autorizado",
            "actividad no autorizada",
        ],
        "security key change": [
            "clave ssh agregada",
            "clave ssh añadida",
            "se agregó una clave ssh",
            "se agrego una clave ssh",
            "se añadió una clave ssh",
            "se anadio una clave ssh",
            "clave pública agregada",
            "clave publica agregada",
            "clave pública añadida",
            "clave publica añadida",
            "clave gpg agregada",
            "clave gpg añadida",
        ],
    },
    "auth_code_labels": [
        "código",
        "codigo",
        "código de verificación",
        "codigo de verificacion",
        "código de autenticación",
        "codigo de autenticacion",
        "código de inicio de sesión",
        "codigo de inicio de sesion",
        "código de seguridad",
        "codigo de seguridad",
        "pin",
    ],
    "private_field_labels": [
        "correo electrónico",
        "correo electronico",
        "email",
        "teléfono",
        "telefono",
        "dirección",
        "direccion",
        "contacto",
        "asistente",
        "destinatario",
        "remitente",
        "nombre completo",
        "nombre",
        "apellido",
        "fecha de nacimiento",
        "pasaporte",
    ],
    "browser_private_context_terms": [
        "sesión iniciada",
        "sesion iniciada",
        "cerrar sesión",
        "cerrar sesion",
        "mi cuenta",
        "cuenta",
        "perfil",
        "autenticado",
        "contraseña",
        "contrasena",
    ],
    "redaction_markers": [
        "asunto de correo sensible redactado",
        "contenido de correo sensible redactado",
        "mensaje de correo sensible redactado",
        "asunto sensible redactado",
    ],
    "redacted_security_terms": [
        "contraseña",
        "contrasena",
        "restablecer",
        "recuperar",
        "verificar",
        "verificación",
        "verificacion",
        "autenticación",
        "autenticacion",
        "inicio de sesión",
        "inicio de sesion",
        "token",
        "código",
        "codigo",
        "seguridad",
        "clave",
        "enlace mágico",
        "enlace magico",
    ],
    "security_link_terms": [
        "verificar",
        "confirmar",
        "recuperar",
        "restablecer",
        "contraseña",
        "contrasena",
    ],
}
