"""French semantic detection terms."""

from __future__ import annotations

PACK = {
    "id": "fr",
    "name": "French",
    "security_sensitive_phrases": {
        "password reset": [
            "réinitialiser le mot de passe",
            "réinitialiser votre mot de passe",
            "modifier le mot de passe",
            "changer votre mot de passe",
            "mot de passe oublié",
        ],
        "account recovery": [
            "récupération de compte",
            "récupérer votre compte",
            "récupérer le compte",
        ],
        "one-time code": [
            "code à usage unique",
            "mot de passe temporaire",
            "code temporaire",
            "code unique",
        ],
        "multi-factor auth": [
            "authentification à deux facteurs",
            "validation en deux étapes",
            "authentification multifacteur",
            "2fa",
            "mfa",
        ],
        "magic link": [
            "lien magique",
        ],
        "account verification": [
            "vérifiez votre e-mail",
            "vérifier votre e-mail",
            "vérifiez votre compte",
            "vérifier votre compte",
            "vérifiez votre identité",
        ],
        "account confirmation": [
            "confirmez votre e-mail",
            "confirmer votre e-mail",
            "confirmez votre compte",
            "confirmation de compte",
        ],
        "security alert": [
            "alerte de sécurité",
            "nouvelle connexion",
            "connexion suspecte",
            "activité suspecte",
            "connexion non autorisée",
            "activité non autorisée",
        ],
        "security key change": [
            "clé ssh ajoutée",
            "clé ssh supprimée",
            "clé publique ajoutée",
            "clé publique supprimée",
            "clé gpg ajoutée",
        ],
    },
    "auth_code_labels": [
        "code",
        "otp",
        "pin",
        "code de vérification",
        "code d'authentification",
        "code de connexion",
        "code de sécurité",
    ],
    "private_field_labels": [
        "e-mail",
        "courriel",
        "téléphone",
        "adresse",
        "contact",
        "participant",
        "destinataire",
        "expéditeur",
        "nom complet",
        "prénom",
        "nom de famille",
        "date de naissance",
        "passeport",
    ],
    "browser_private_context_terms": [
        "connecté",
        "déconnexion",
        "se déconnecter",
        "mon compte",
        "compte",
        "profil",
        "authentifié",
        "mot de passe",
    ],
    "redaction_markers": [
        "objet d'e-mail sensible masqué",
        "contenu d'e-mail sensible masqué",
        "message d'e-mail sensible masqué",
    ],
    "redacted_security_terms": [
        "mot de passe",
        "réinitialiser",
        "récupérer",
        "vérifier",
        "vérification",
        "authentification",
        "connexion",
        "otp",
        "code",
        "sécurité",
        "clé",
    ],
    "security_link_terms": [
        "reset",
        "verify",
        "confirm",
        "réinitialiser",
        "recuperer",
        "récupérer",
        "vérifier",
        "confirmer",
        "mot-de-passe",
    ],
}
