"""Indonesian semantic detection terms."""

from __future__ import annotations

PACK = {
    "id": "id",
    "name": "Indonesian",
    "security_sensitive_phrases": {
        "password reset": [
            "reset kata sandi",
            "atur ulang kata sandi",
            "ubah kata sandi",
            "lupa kata sandi",
            "pemulihan kata sandi",
        ],
        "account recovery": [
            "pemulihan akun",
            "pulihkan akun",
            "memulihkan akun",
        ],
        "one-time code": [
            "kode sekali pakai",
            "kata sandi sementara",
            "kode sementara",
            "one time password",
        ],
        "multi-factor auth": [
            "autentikasi dua faktor",
            "verifikasi dua langkah",
            "autentikasi multifaktor",
            "2fa",
            "mfa",
        ],
        "magic link": [
            "tautan ajaib",
            "link ajaib",
        ],
        "account verification": [
            "verifikasi email anda",
            "verifikasi akun anda",
            "verifikasi identitas anda",
            "verifikasi akun",
        ],
        "account confirmation": [
            "konfirmasi email anda",
            "konfirmasi akun anda",
            "konfirmasi akun",
        ],
        "security alert": [
            "peringatan keamanan",
            "login baru",
            "masuk baru",
            "login mencurigakan",
            "aktivitas mencurigakan",
            "aktivitas tidak sah",
        ],
        "security key change": [
            "kunci ssh ditambahkan",
            "kunci ssh dihapus",
            "kunci publik ditambahkan",
            "kunci publik dihapus",
            "kunci gpg ditambahkan",
        ],
    },
    "auth_code_labels": [
        "kode",
        "otp",
        "pin",
        "kode verifikasi",
        "kode autentikasi",
        "kode login",
        "kode keamanan",
    ],
    "private_field_labels": [
        "email",
        "telepon",
        "alamat",
        "kontak",
        "peserta",
        "penerima",
        "pengirim",
        "nama lengkap",
        "nama depan",
        "nama belakang",
        "tanggal lahir",
        "paspor",
    ],
    "browser_private_context_terms": [
        "sudah masuk",
        "keluar",
        "logout",
        "akun saya",
        "akun",
        "profil",
        "terautentikasi",
        "kata sandi",
    ],
    "redaction_markers": [
        "subjek email sensitif disunting",
        "konten email sensitif disunting",
        "pesan email sensitif disunting",
    ],
    "redacted_security_terms": [
        "kata sandi",
        "reset",
        "pulihkan",
        "verifikasi",
        "autentikasi",
        "login",
        "otp",
        "kode",
        "keamanan",
        "kunci",
    ],
    "security_link_terms": [
        "reset",
        "verify",
        "confirm",
        "verifikasi",
        "konfirmasi",
        "pulihkan",
        "kata-sandi",
        "kode",
        "otp",
    ],
}
