"""Korean semantic detection terms."""

from __future__ import annotations

PACK = {
    "id": "ko",
    "name": "Korean",
    "security_sensitive_phrases": {
        "password reset": [
            "비밀번호 재설정",
            "비밀번호를 재설정",
            "비밀번호 변경",
            "비밀번호를 잊으셨나요",
            "비밀번호 복구",
        ],
        "account recovery": [
            "계정 복구",
            "계정을 복구",
            "계정 되찾기",
        ],
        "one-time code": [
            "일회용 코드",
            "일회용 비밀번호",
            "임시 비밀번호",
            "임시 코드",
        ],
        "multi-factor auth": [
            "이중 인증",
            "2단계 인증",
            "다중 인증",
            "2fa",
            "mfa",
        ],
        "magic link": [
            "매직 링크",
            "로그인 링크",
        ],
        "account verification": [
            "이메일을 확인",
            "계정을 확인",
            "신원을 확인",
            "계정 확인",
        ],
        "account confirmation": [
            "이메일을 승인",
            "계정을 승인",
            "계정 승인",
        ],
        "security alert": [
            "보안 경고",
            "새 로그인",
            "의심스러운 로그인",
            "의심스러운 활동",
            "승인되지 않은 활동",
        ],
        "security key change": [
            "ssh 키가 추가되었습니다",
            "ssh 키가 제거되었습니다",
            "공개 키가 추가되었습니다",
            "공개 키가 제거되었습니다",
            "gpg 키가 추가되었습니다",
        ],
    },
    "auth_code_labels": [
        "코드",
        "otp",
        "pin",
        "인증 코드",
        "확인 코드",
        "로그인 코드",
        "보안 코드",
        "일회용 코드",
    ],
    "private_field_labels": [
        "이메일",
        "전화",
        "주소",
        "연락처",
        "참석자",
        "수신자",
        "발신자",
        "전체 이름",
        "이름",
        "생년월일",
        "여권",
    ],
    "browser_private_context_terms": [
        "로그인됨",
        "로그아웃",
        "내 계정",
        "계정",
        "프로필",
        "인증됨",
        "비밀번호",
    ],
    "redaction_markers": [
        "민감한 이메일 제목이 수정됨",
        "민감한 이메일 내용이 수정됨",
        "민감한 이메일 메시지가 수정됨",
    ],
    "redacted_security_terms": [
        "비밀번호",
        "재설정",
        "복구",
        "확인",
        "인증",
        "로그인",
        "otp",
        "코드",
        "보안",
        "키",
    ],
    "security_link_terms": [
        "reset",
        "verify",
        "confirm",
        "재설정",
        "복구",
        "확인",
        "인증",
        "비밀번호",
        "코드",
    ],
}
