"""Nigerian Pidgin semantic detection terms."""

from __future__ import annotations

PACK = {
    "id": "pcm",
    "name": "Nigerian Pidgin",
    "security_sensitive_phrases": {
        "password reset": [
            "reset your password",
            "reset ya password",
            "change your password",
            "change ya password",
            "forgot your password",
            "recover password",
        ],
        "account recovery": [
            "recover your account",
            "recover ya account",
            "account recovery",
        ],
        "one-time code": [
            "one time code",
            "one-time code",
            "temporary password",
            "temporary code",
        ],
        "multi-factor auth": [
            "two factor",
            "two step verification",
            "multi factor",
            "2fa",
            "mfa",
        ],
        "magic link": [
            "magic link",
            "login link",
        ],
        "account verification": [
            "verify your email",
            "verify ya email",
            "verify your account",
            "verify ya account",
            "verify your identity",
        ],
        "account confirmation": [
            "confirm your email",
            "confirm ya email",
            "confirm your account",
            "confirm ya account",
        ],
        "security alert": [
            "security alert",
            "new login",
            "new sign in",
            "suspicious login",
            "suspicious activity",
            "unauthorized activity",
        ],
        "security key change": [
            "ssh key added",
            "ssh key removed",
            "public key added",
            "public key removed",
            "gpg key added",
        ],
    },
    "auth_code_labels": [
        "code",
        "otp",
        "pin",
        "verification code",
        "auth code",
        "login code",
        "security code",
        "one time code",
    ],
    "private_field_labels": [
        "email",
        "phone",
        "address",
        "contact",
        "person",
        "receiver",
        "sender",
        "full name",
        "first name",
        "last name",
        "date of birth",
        "passport",
    ],
    "browser_private_context_terms": [
        "logged in",
        "sign out",
        "logout",
        "my account",
        "account",
        "profile",
        "authenticated",
        "password",
    ],
    "redaction_markers": [
        "sensitive email subject redacted",
        "sensitive email content redacted",
        "sensitive email message redacted",
    ],
    "redacted_security_terms": [
        "password",
        "reset",
        "recover",
        "verify",
        "auth",
        "login",
        "otp",
        "code",
        "security",
        "key",
    ],
    "security_link_terms": [
        "reset",
        "recover",
        "verify",
        "confirm",
        "password",
        "otp",
    ],
}
