"""Portuguese semantic detection terms."""

from __future__ import annotations

PACK = {
    "id": "pt",
    "name": "Portuguese",
    "security_sensitive_phrases": {
        "password reset": [
            "redefinir senha",
            "redefinir sua senha",
            "alterar senha",
            "mudar sua senha",
            "esqueceu sua senha",
            "recuperar senha",
        ],
        "account recovery": [
            "recuperação de conta",
            "recuperar sua conta",
            "recuperar conta",
        ],
        "one-time code": [
            "código de uso único",
            "codigo de uso unico",
            "senha temporária",
            "senha temporaria",
            "código temporário",
            "codigo temporario",
        ],
        "multi-factor auth": [
            "autenticação de dois fatores",
            "autenticacao de dois fatores",
            "verificação em duas etapas",
            "verificacao em duas etapas",
            "autenticação multifator",
            "2fa",
            "mfa",
        ],
        "magic link": [
            "link mágico",
            "link magico",
        ],
        "account verification": [
            "verifique seu e-mail",
            "verificar seu e-mail",
            "verifique sua conta",
            "verificar sua conta",
            "verifique sua identidade",
        ],
        "account confirmation": [
            "confirme seu e-mail",
            "confirmar seu e-mail",
            "confirme sua conta",
            "confirmação de conta",
        ],
        "security alert": [
            "alerta de segurança",
            "alerta de seguranca",
            "novo login",
            "login suspeito",
            "atividade suspeita",
            "login não autorizado",
            "atividade não autorizada",
        ],
        "security key change": [
            "chave ssh adicionada",
            "chave ssh removida",
            "chave pública adicionada",
            "chave publica adicionada",
            "chave gpg adicionada",
        ],
    },
    "auth_code_labels": [
        "código",
        "codigo",
        "otp",
        "pin",
        "código de verificação",
        "codigo de verificacao",
        "código de autenticação",
        "codigo de autenticacao",
        "código de login",
        "codigo de login",
        "código de segurança",
        "codigo de seguranca",
    ],
    "private_field_labels": [
        "e-mail",
        "email",
        "telefone",
        "endereço",
        "endereco",
        "contato",
        "participante",
        "destinatário",
        "destinatario",
        "remetente",
        "nome completo",
        "nome",
        "sobrenome",
        "data de nascimento",
        "passaporte",
    ],
    "browser_private_context_terms": [
        "conectado",
        "sair",
        "logout",
        "minha conta",
        "conta",
        "perfil",
        "autenticado",
        "senha",
    ],
    "redaction_markers": [
        "assunto de e-mail sensível redigido",
        "conteúdo de e-mail sensível redigido",
        "mensagem de e-mail sensível redigida",
    ],
    "redacted_security_terms": [
        "senha",
        "redefinir",
        "recuperar",
        "verificar",
        "verificação",
        "autenticação",
        "login",
        "otp",
        "código",
        "codigo",
        "segurança",
        "chave",
    ],
    "security_link_terms": [
        "reset",
        "verify",
        "confirm",
        "redefinir",
        "recuperar",
        "verificar",
        "confirmar",
        "senha",
    ],
}
