"""Tagalog/Filipino semantic detection terms."""

from __future__ import annotations

PACK = {
    "id": "tl",
    "name": "Tagalog/Filipino",
    "security_sensitive_phrases": {
        "password reset": [
            "i-reset ang password",
            "reset ang password",
            "palitan ang password",
            "nakalimutan ang password",
            "bawiin ang password",
        ],
        "account recovery": [
            "pagbawi ng account",
            "bawiin ang account",
            "ibalik ang account",
        ],
        "one-time code": [
            "one-time code",
            "isang beses na code",
            "pansamantalang password",
            "pansamantalang code",
        ],
        "multi-factor auth": [
            "two-factor authentication",
            "dalawang hakbang na beripikasyon",
            "multi-factor authentication",
            "2fa",
            "mfa",
        ],
        "magic link": [
            "magic link",
            "link sa pag-login",
        ],
        "account verification": [
            "i-verify ang iyong email",
            "i-verify ang iyong account",
            "i-verify ang iyong pagkakakilanlan",
            "beripikasyon ng account",
        ],
        "account confirmation": [
            "kumpirmahin ang iyong email",
            "kumpirmahin ang iyong account",
            "kumpirmasyon ng account",
        ],
        "security alert": [
            "alerto sa seguridad",
            "bagong login",
            "kahina-hinalang login",
            "kahina-hinalang aktibidad",
            "hindi awtorisadong aktibidad",
        ],
        "security key change": [
            "idinagdag ang ssh key",
            "tinanggal ang ssh key",
            "idinagdag ang public key",
            "tinanggal ang public key",
            "idinagdag ang gpg key",
        ],
    },
    "auth_code_labels": [
        "code",
        "otp",
        "pin",
        "verification code",
        "code ng beripikasyon",
        "authentication code",
        "login code",
        "security code",
    ],
    "private_field_labels": [
        "email",
        "telepono",
        "address",
        "tirahan",
        "contact",
        "tatanggap",
        "nagpadala",
        "buong pangalan",
        "pangalan",
        "apelyido",
        "petsa ng kapanganakan",
        "pasaporte",
    ],
    "browser_private_context_terms": [
        "naka-login",
        "mag-sign out",
        "logout",
        "aking account",
        "account",
        "profile",
        "authenticated",
        "password",
    ],
    "redaction_markers": [
        "sensitibong paksa ng email ay tinakpan",
        "sensitibong nilalaman ng email ay tinakpan",
        "sensitibong mensahe ng email ay tinakpan",
    ],
    "redacted_security_terms": [
        "password",
        "reset",
        "bawiin",
        "verify",
        "beripikasyon",
        "authentication",
        "login",
        "otp",
        "code",
        "seguridad",
        "key",
    ],
    "security_link_terms": [
        "reset",
        "verify",
        "confirm",
        "bawiin",
        "kumpirmahin",
        "password",
        "code",
        "otp",
    ],
}
