"""Turkish semantic detection terms."""

from __future__ import annotations

PACK = {
    "id": "tr",
    "name": "Turkish",
    "security_sensitive_phrases": {
        "password reset": [
            "şifre sıfırlama",
            "şifrenizi sıfırlayın",
            "parola sıfırlama",
            "şifre değiştirme",
            "şifremi unuttum",
            "parolamı unuttum",
        ],
        "account recovery": [
            "hesap kurtarma",
            "hesabınızı kurtarın",
            "hesabı geri al",
        ],
        "one-time code": [
            "tek kullanımlık kod",
            "tek seferlik kod",
            "geçici şifre",
            "geçici kod",
        ],
        "multi-factor auth": [
            "iki faktörlü kimlik doğrulama",
            "iki adımlı doğrulama",
            "çok faktörlü kimlik doğrulama",
            "2fa",
            "mfa",
        ],
        "magic link": [
            "sihirli bağlantı",
            "giriş bağlantısı",
        ],
        "account verification": [
            "e-postanızı doğrulayın",
            "hesabınızı doğrulayın",
            "kimliğinizi doğrulayın",
            "hesap doğrulama",
        ],
        "account confirmation": [
            "e-postanızı onaylayın",
            "hesabınızı onaylayın",
            "hesap onayı",
        ],
        "security alert": [
            "güvenlik uyarısı",
            "yeni giriş",
            "şüpheli giriş",
            "şüpheli etkinlik",
            "yetkisiz etkinlik",
        ],
        "security key change": [
            "ssh anahtarı eklendi",
            "ssh anahtarı kaldırıldı",
            "genel anahtar eklendi",
            "genel anahtar kaldırıldı",
            "gpg anahtarı eklendi",
        ],
    },
    "auth_code_labels": [
        "kod",
        "otp",
        "pin",
        "doğrulama kodu",
        "kimlik doğrulama kodu",
        "giriş kodu",
        "güvenlik kodu",
    ],
    "private_field_labels": [
        "e-posta",
        "email",
        "telefon",
        "adres",
        "iletişim",
        "katılımcı",
        "alıcı",
        "gönderen",
        "tam ad",
        "ad",
        "soyad",
        "doğum tarihi",
        "pasaport",
    ],
    "browser_private_context_terms": [
        "giriş yapıldı",
        "çıkış yap",
        "logout",
        "hesabım",
        "hesap",
        "profil",
        "kimliği doğrulanmış",
        "şifre",
    ],
    "redaction_markers": [
        "hassas e-posta konusu gizlendi",
        "hassas e-posta içeriği gizlendi",
        "hassas e-posta mesajı gizlendi",
    ],
    "redacted_security_terms": [
        "şifre",
        "parola",
        "sıfırla",
        "kurtar",
        "doğrula",
        "kimlik doğrulama",
        "giriş",
        "kod",
        "güvenlik",
        "anahtar",
    ],
    "security_link_terms": [
        "reset",
        "verify",
        "confirm",
        "sifirla",
        "sıfırla",
        "kurtar",
        "dogrula",
        "doğrula",
        "onayla",
        "sifre",
        "şifre",
    ],
}
