"""Vietnamese semantic detection terms."""

from __future__ import annotations

PACK = {
    "id": "vi",
    "name": "Vietnamese",
    "security_sensitive_phrases": {
        "password reset": [
            "đặt lại mật khẩu",
            "dat lai mat khau",
            "khôi phục mật khẩu",
            "khoi phuc mat khau",
            "đổi mật khẩu",
            "quên mật khẩu",
        ],
        "account recovery": [
            "khôi phục tài khoản",
            "khoi phuc tai khoan",
            "lấy lại tài khoản",
            "lay lai tai khoan",
        ],
        "one-time code": [
            "mã dùng một lần",
            "ma dung mot lan",
            "mật khẩu tạm thời",
            "mat khau tam thoi",
            "mã tạm thời",
        ],
        "multi-factor auth": [
            "xác thực hai yếu tố",
            "xac thuc hai yeu to",
            "xác minh hai bước",
            "xác thực đa yếu tố",
            "2fa",
            "mfa",
        ],
        "magic link": [
            "liên kết ma thuật",
            "lien ket ma thuat",
            "liên kết đăng nhập",
        ],
        "account verification": [
            "xác minh email của bạn",
            "xác minh tài khoản của bạn",
            "xác minh danh tính của bạn",
            "xác minh tài khoản",
        ],
        "account confirmation": [
            "xác nhận email của bạn",
            "xác nhận tài khoản của bạn",
            "xác nhận tài khoản",
        ],
        "security alert": [
            "cảnh báo bảo mật",
            "canh bao bao mat",
            "đăng nhập mới",
            "đăng nhập đáng ngờ",
            "hoạt động đáng ngờ",
            "hoạt động trái phép",
        ],
        "security key change": [
            "đã thêm khóa ssh",
            "đã xóa khóa ssh",
            "đã thêm khóa công khai",
            "đã xóa khóa công khai",
            "đã thêm khóa gpg",
        ],
    },
    "auth_code_labels": [
        "mã",
        "ma",
        "otp",
        "pin",
        "mã xác minh",
        "ma xac minh",
        "mã xác thực",
        "mã đăng nhập",
        "mã bảo mật",
    ],
    "private_field_labels": [
        "email",
        "điện thoại",
        "dien thoai",
        "địa chỉ",
        "dia chi",
        "liên hệ",
        "người nhận",
        "người gửi",
        "họ tên",
        "tên",
        "ngày sinh",
        "hộ chiếu",
    ],
    "browser_private_context_terms": [
        "đã đăng nhập",
        "dang nhap",
        "đăng xuất",
        "dang xuat",
        "tài khoản của tôi",
        "tài khoản",
        "hồ sơ",
        "đã xác thực",
        "mật khẩu",
    ],
    "redaction_markers": [
        "chủ đề email nhạy cảm đã bị biên tập",
        "nội dung email nhạy cảm đã bị biên tập",
        "tin nhắn email nhạy cảm đã bị biên tập",
    ],
    "redacted_security_terms": [
        "mật khẩu",
        "mat khau",
        "đặt lại",
        "khôi phục",
        "xác minh",
        "xác thực",
        "đăng nhập",
        "otp",
        "mã",
        "bảo mật",
        "khóa",
    ],
    "security_link_terms": [
        "reset",
        "verify",
        "confirm",
        "dat-lai",
        "đặt-lại",
        "khoi-phuc",
        "khôi-phục",
        "xac-minh",
        "xác-minh",
        "mat-khau",
        "mật-khẩu",
        "ma",
        "mã",
    ],
}
